[package]
name = "quamatic/virtua"
description = "An easy way to create virtualized lists and grids."
version = "0.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
FenwickTree = "quamatic/fenwick-tree@0.1.0"
